### PR TITLE
feature: added badge

### PR DESCRIPTION
**Pull request by omgaikwad**
Preview Link:   https://deploy-preview-3--zen-hopper-5023d4.netlify.app/

Screenshot (26)
Screenshot (27)

### CODE REVIEW

**Review by horsemaker — APPROVED** [review]
Looks great to me!

**Review by vijaytembugade — APPROVED** [review]
Amazing styling yaar.. 
I like it.
Just work on responsiveness now!

**Comment by SanjayJatti** [comment]
Looking clean and awesome. You can merge it.

**Comment by omgaikwad** [comment]
Thanks for your compliments! I will merge it.

**Comment by omgaikwad** [comment]
> Amazing styling yaar.. I like it. Just work on responsiveness now!

Yes I will make it responsive at the end. Thank you for review!

**Pull request merged**
